### PR TITLE
ISSUE-9: Fix JSON parsing dash type by surrounding in quotes

### PR DESCRIPTION
**Pull request by natdm**
Made a switch statement to fix the immediate issue, but took notes on being able to parse generally bad characters for each language.

### CODE REVIEW

**Comment by scottmmjackson** [comment]
Cool! If you'd like, I can submit a follow-on with an "isValidEsIdentifier" helper, unless you're already in the midst of that?

**Comment by natdm** [comment]
I've not got any kind of a plan for that. What would it do and how would it be used? Maybe make an issue/proposal with those details.

**Comment by scottmmjackson** [comment]
Sure, right around here: https://github.com/natdm/typewriter/blob/master/template/template.go#L230

You've got `strings.Contains(t.name, '-')`. That test could be generalized to check for anything that makes the identifier invalid. Here's a basic attempt:

```
var ecmaReservedWords = map[string]struct{}{
 "break": struct{}{},
"case": struct{}{},
 "catch": struct{}{},
"class": struct{}{},
"const": struct{}{},
"continue": struct{}{},
"debugger": struct{}{},
"default": struct{}{},
"delete": struct{}{},
"do": struct{}{},
"else": struct{}{},
"export": struct{}{},
"extends": struct{}{},
"finally": struct{}{},
"for": struct{}{},
"function": struct{}{},
"if": struct{}{},
"import": struct{}{},
"in": struct{}{},
"instanceof": struct{}{},
"new": struct{}{},
"return": struct{}{},
"super": struct{}{},
"switch": struct{}{},
"this": struct{}{},
"throw": struct{}{},
"try": struct{}{},
"typeof": struct{}{},
"var": struct{}{},
"void": struct{}{},
"while": struct{}{},
"with": struct{}{},
"yield": struct{}{},
"enum": struct{}{},
"implements": struct{}{},
"interface": struct{}{},
"let": struct{}{},
"package": struct{}{},
"private": struct{}{},
"protected": struct{}{},
"public": struct{}{},
"static": struct{}{},
"abstract": struct{}{},
"boolean": struct{}{},
"byte": struct{}{},
"char": struct{}{},
"double": struct{}{},
"final": struct{}{},
"float": struct{}{},
"goto": struct{}{},
"int": struct{}{},
"long": struct{}{},
"native": struct{}{},
"short": struct{}{},
"synchronized": struct{}{},
"throws": struct{}{},
"transient": struct{}{},
"volatile": struct{}{},
"await": struct{}{},
}

// Greedy regex that permits common valid identifiers like `$apply` or `_`
// This quotes more than is strictly necessary, because unicode "letters" in identifier names
// are valid. See: https://stackoverflow.com/questions/2008279/validate-a-javascript-function-name
var validIdentifier = regex.MustCompile(`^[$\w]+$`)

func propertyShouldBeQuoted(name string) bool {
  _, isReservedWord := ecmaReservedWords[name]
  return isReservedWord || !validIdentifier.MatchString(name) 
}
```

See playground here: https://play.golang.org/p/SxVqckRKZ3

Note that this attempt is a little overkill, and will quote valid identifiers, but they'd be uncommon valid identifiers and it would ensure that the tool always works.

**Comment by natdm** [comment]
Opened an issue for this discussion.

**Pull request merged**
